// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBawmSMxFvmvYYqKsXrdGeM7qMcl3tY2xY',
    appId: '1:164318871718:web:dbd1c47a1c851e1440b467',
    messagingSenderId: '164318871718',
    projectId: 'youphoria-813bb',
    authDomain: 'youphoria-813bb.firebaseapp.com',
    storageBucket: 'youphoria-813bb.appspot.com',
    measurementId: 'G-9WEE6K5EGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzp7QoUrk0Zon6aazCgk-p8rP4HLk7SI',
    appId: '1:164318871718:android:2d349f993dc8a6de40b467',
    messagingSenderId: '164318871718',
    projectId: 'youphoria-813bb',
    storageBucket: 'youphoria-813bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlbDHnx9u_QeUtU7stM6EHmHNCJTXrz2w',
    appId: '1:164318871718:ios:4bb499034395108b40b467',
    messagingSenderId: '164318871718',
    projectId: 'youphoria-813bb',
    storageBucket: 'youphoria-813bb.appspot.com',
    iosClientId: '164318871718-8j99qbdccjvcg4u2m3hqg8urbrsishk6.apps.googleusercontent.com',
    iosBundleId: 'io.halcyoncore.youphoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlbDHnx9u_QeUtU7stM6EHmHNCJTXrz2w',
    appId: '1:164318871718:ios:4bb499034395108b40b467',
    messagingSenderId: '164318871718',
    projectId: 'youphoria-813bb',
    storageBucket: 'youphoria-813bb.appspot.com',
    iosClientId: '164318871718-8j99qbdccjvcg4u2m3hqg8urbrsishk6.apps.googleusercontent.com',
    iosBundleId: 'io.halcyoncore.youphoria',
  );
}
