export 'Communication.dart';
// export 'Communication.dart';
// export 'Consent.dart';
// export 'Contraception.dart';
// export 'Gender.dart';
// export 'Hotlines.dart';
// export 'Puberty.dart';
// export 'Resources.dart';
// export 'SexualOrientation.dart';
// export 'Sti.dart';

import 'Communication.dart';
import 'Consent.dart';
import 'Contraception.dart';
import 'Gender.dart';
import 'Hotlines.dart';
import 'Puberty.dart';
import 'Resources.dart';
import 'SexualOrientation.dart';
import 'Sti.dart';

Communication communication_obj = Communication();
Consent consent_obj = Consent();
Contraception contraception_obj = Contraception();
Gender gender_obj = Gender();
Hotlines hotlines_obj = Hotlines();
Puberty puberty_obj = Puberty();
Resources resources_obj = Resources();
SexualOrientation sexualOrientation_obj = SexualOrientation();
Sti sti_obj = Sti();
